# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
