# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0002_auto_20161203_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
