# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0004_auto_20170214_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='id',
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False),
        ),
    ]
