# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0005_auto_20170222_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='active',
        ),
    ]
