# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0006_remove_plugin_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='plugins',
            field=models.ManyToManyField(to='gitmate_config.Plugin'),
        ),
    ]
