# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitmate_config', '0007_repository_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='admins',
            field=models.ManyToManyField(related_name='admin_repos', to=settings.AUTH_USER_MODEL),
        ),
    ]
