# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0008_repository_admins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
    ]
