# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0009_auto_20170622_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
