# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 09:52
from __future__ import unicode_literals

from django.db import migrations
from IGitt.GitHub.GitHubRepository import GitHubRepository
from IGitt.GitLab.GitLabRepository import GitLabRepository

from gitmate_config import Providers


# this method is required and `repo.igitt_repo` can't be communicated via the
# object received via `apps.get_model`.
def _get_igitt_repo(repo):
    """
    Returns an IGitt Repository object from Repository model.
    """
    token_str = repo.user.social_auth.get(
        provider=repo.provider).extra_data['access_token']
    if repo.provider == Providers.GITHUB.value:
        token = Providers.GITHUB.get_token(token_str)
        return GitHubRepository(token, repo.full_name)
    if repo.provider == Providers.GITLAB.value:
        token = Providers.GITLAB.get_token(token_str)
        return GitLabRepository(token, repo.full_name)


def link_repos_to_orgs(apps, schema_editor):
    Organization = apps.get_model('gitmate_config', 'Organization')
    Repository = apps.get_model('gitmate_config', 'Repository')

    for repo in Repository.objects.all():
        irepo = _get_igitt_repo(repo)

        org, _ = Organization.objects.get_or_create(
            name=irepo.top_level_org.name,
            provider=irepo.hoster,
            defaults={'primary_user': repo.user})
        org.save()

        repo.org=org
        repo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0011_repository_org'),
    ]

    operations = [
        migrations.RunPython(link_repos_to_orgs)
    ]
