# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0011_repository_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='gitmate_config.Organization')),
            ],
        ),
    ]
