# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0011_repository_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='identifier',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
