# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0012_repository_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='activation_count',
            field=models.IntegerField(default=0),
        ),
    ]
