# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0013_repository_activation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default=None, max_length=32)),
                ('identifier', models.IntegerField(default=-1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='installation',
            unique_together=set([('provider', 'identifier')]),
        ),
    ]
