# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0014_auto_20171208_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='installation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='gitmate_config.Installation'),
        ),
    ]
