# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gitmate_config', '0016_auto_20171213_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='admins',
            field=models.ManyToManyField(related_name='installations', to=settings.AUTH_USER_MODEL),
        ),
    ]
