# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0017_installation_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='installation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repos', to='gitmate_config.Installation'),
        ),
    ]
