# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('gitmate_config', '0020_auto_20180130_0748'), ('gitmate_config', '0021_auto_20180220_0845')]

    dependencies = [
        ('gitmate_config', '0019_change_pk_to_identifier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([('provider', 'identifier')]),
        ),
    ]
