# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0019_change_pk_to_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='identifier',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([('provider', 'identifier')]),
        ),
    ]
