# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0020_auto_20180130_0748_squashed_0021_auto_20180220_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='identifier',
            field=models.IntegerField(default=None),
        ),
    ]
