# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 06:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_plugins_field(apps, *args):
    Repository = apps.get_model('gitmate_config', 'Repository')
    for repo in Repository.objects.all():
        for plugin in repo.plugins.all():
            repo.temp_plugins.append(plugin.name)
        repo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0021_auto_20180220_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='temp_plugins',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.RunPython(migrate_plugins_field,
                             migrations.RunPython.noop),
    ]
