# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0023_destroy_repository_plugins_table_and_rename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plugin',
        ),
    ]
