# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitmate_config', '0007_repository_plugins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(default='(fix(e[sd])?|close[sd]?|resolve[sd]?) #[1-9][0-9]*', help_text='The pattern to be compared for spotting bugs.', max_length=100)),
                ('hotspot_label', models.CharField(default='review carefully!', help_text='The label to be used to identify possible bugs.', max_length=25)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitmate_bug_spotter_repository', to='gitmate_config.Repository')),
            ],
        ),
    ]
