# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_bug_spotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='repo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitmate_bug_spotter_repository', to='gitmate_config.Repository'),
        ),
    ]
