# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_bug_spotter', '0003_auto_20170622_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='hotspot_label',
            field=models.CharField(default='review carefully!', help_text='Label for pull requests with high risk', max_length=25),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pattern',
            field=models.CharField(default='(fix(e[sd])?|close[sd]?|resolve[sd]?) #[1-9][0-9]*', help_text='Pattern used on commit messages to identify bug fixes', max_length=100),
        ),
    ]
