# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_bug_spotter', '0005_auto_20171205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='pattern',
            field=models.TextField(default='(fix(e[sd])?|close[sd]?|resolve[sd]?) #[1-9][0-9]*', help_text='Pattern used on commit messages to identify bug fixes'),
        ),
    ]
