# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_ack', '0002_auto_20170614_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
    ]
