# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_ack', '0003_auto_20170622_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ack_strs',
            field=models.CharField(default='ack', help_text='Keywords for acknowledging commits, comma separated', max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='unack_strs',
            field=models.CharField(default='unack', help_text='Keywords for unacknowledging commits, comma separated', max_length=100),
        ),
    ]
