# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_ack', '0004_auto_20170706_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ack_strs',
            field=models.CharField(default='ack, reack', help_text='Keywords for acknowledging commits, comma separated', max_length=100),
        ),
    ]
