# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_ack', '0006_mergerequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergerequestmodel',
            name='last_head',
            field=models.CharField(default='', max_length=40),
        ),
    ]
