# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_ack', '0008_auto_20171205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ack_strs',
            field=models.TextField(default='ack, reack', help_text='Keywords for acknowledging commits, comma separated'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='unack_strs',
            field=models.TextField(default='unack', help_text='Keywords for unacknowledging commits, comma separated'),
        ),
    ]
