image: docker:1.10.3
services:
  - docker:dind
  - postgres:9.6
variables:
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres

variables:
  DOCKER_DRIVER: overlay

before_script:
  - export TEST_IMAGE_NAME=registry.gitlab.com/$CI_PROJECT_PATH:${CI_COMMIT_REF_NAME/\//-}-$CI_COMMIT_SHA
  - export IMAGE_NAME=registry.gitlab.com/$CI_PROJECT_PATH:latest
  - export WEBHOOK_SECRET=foobar
  - export COALA_RESULTS_IMAGE=registry.gitlab.com/gitmate/open-source/coala-incremental-results:latest
  - export RESULTS_BOUNCER_IMAGE=registry.gitlab.com/gitmate/open-source/result-bouncer:latest

check_code:
  image: python:3
  script:
  - pip install 'coala-bears[alldeps]'
  - pip install -r requirements.txt
  - coala --ci
  except:
  - master

run_tests:
  image: python:3
  script:
  - pip3 install -r requirements.txt
  - pip3 install -r test-requirements.txt
  - py.test -vv --cov --doctest-modules
  except:
  - master

build_image:
  script:
    - docker build -t $TEST_IMAGE_NAME .
    - docker login -e gitlab-ci@gitlab.com -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push $TEST_IMAGE_NAME
  except:
    - master

release_image:
  script:
    - docker login -e gitlab-ci@gitlab.com -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - master
