image: docker:1.10.3
services:
  - docker:dind
  - postgres:9.6
variables:
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres

stages:
  - test
  - build
  - release

variables:
  DOCKER_DRIVER: overlay

before_script:
  - export TEST_IMAGE_NAME=registry.gitlab.com/$CI_PROJECT_PATH:${CI_COMMIT_REF_NAME/\//-}-$CI_COMMIT_SHA
  - export IMAGE_NAME=registry.gitlab.com/$CI_PROJECT_PATH:latest
  - export GITHUB_WEBHOOK_SECRET=foobar
  - export COALA_RESULTS_IMAGE=registry.gitlab.com/gitmate/open-source/coala-incremental-results:latest
  - export RESULTS_BOUNCER_IMAGE=registry.gitlab.com/gitmate/open-source/result-bouncer:latest


check_code:
  image: coala/base:0.10
  stage: test
  script:
  - pip install -r requirements.txt
  - coala --ci

run_tests:
  image: python:3
  stage: test
  script:
  - pip3 install -r requirements.txt
  - pip3 install pytest pytest-cov pytest-django
  - py.test -vv --cov --doctest-modules

build_image:
  stage: build
  script:
    - docker build -t $TEST_IMAGE_NAME .
    - docker login -e gitlab-ci@gitlab.com -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push $TEST_IMAGE_NAME

release_image:
  stage: release
  script:
    - docker login -e gitlab-ci@gitlab.com -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $TEST_IMAGE_NAME
    - docker tag $TEST_IMAGE_NAME $IMAGE_NAME
    - docker push $IMAGE_NAME
  only:
    - master
