version: '3'
services:
  dind:
    image: docker:stable-dind
    privileged: true
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file: ./docker/environment
    links:
      - db
      - rabbit
    depends_on:
      - db
  worker:
    build: .
    command: ./docker/run-worker.sh
    env_file: ./docker/environment
    environment:
      - DOCKER_HOST=tcp://dind:2375
    links:
      - db
      - rabbit
      - dind
    depends_on:
      - rabbit
      - backend
      - dind
  beat:
    build: .
    command: ./docker/run-beat.sh
    env_file: ./docker/environment
    links:
      - db
      - rabbit
    depends_on:
      - rabbit
      - backend
