# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_approver', '0002_auto_20170807_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='approved_label',
            field=models.CharField(default='status/approved', help_text='Label for approved pull requests', max_length=40),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status_labels',
            field=models.CharField(default='process/pending_review, process/WIP', help_text='Labels to be removed from the pull request on approval (comma separated', max_length=500),
        ),
    ]
