# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_approver', '0002_auto_20170807_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='mark_wip_on_ci_fail',
            field=models.BooleanField(default=True),
        ),
    ]
