# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_approver', '0003_auto_20171205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='approved_label',
            field=models.CharField(default='status/ci-approved', max_length=40),
        ),
    ]
