# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_pr_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='sync_assignees',
            field=models.BooleanField(default=True, help_text='Synchronize assignees along with the labels.'),
        ),
    ]
