# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 04:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_pr_sync', '0003_auto_20171205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergerequestmodel',
            name='closes_issues',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
