# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_pr_size_labeller', '0002_auto_20170608_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='repo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gitmate_config.Repository'),
        ),
    ]
