# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 08:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitmate_config', '0007_repository_plugins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted_labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=20), default=['invalid', 'duplicate', 'bounty'], help_text='The labels to be avoided on issues.', size=None)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitmate_issue_labeller_repository', to='gitmate_config.Repository')),
            ],
        ),
    ]
