# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 12:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_labeller', '0003_auto_20170622_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Comma seperated keywords (values) triggering labels (keys) to be set; e.g. type/bug: bug, crash.'),
        ),
    ]
