# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_labeller', '0004_settings_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='blacklisted_labels',
        ),
    ]
