# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_labeller', '0005_remove_settings_blacklisted_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='label_texts_as_keywords',
            field=models.BooleanField(default=True, help_text='Apply labels if they are mentioned in the issue body automatically.'),
        ),
    ]
