# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_labeller', '0007_auto_20171205_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='label_texts_as_keywords',
            field=models.BooleanField(default=False, help_text='Apply labels if they are mentioned in the issue body automatically.'),
        ),
    ]
