# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 04:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_labeller', '0008_auto_20171220_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='keywords',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Comma seperated keywords (values) triggering labels (keys) to be set; e.g. type/bug: bug, crash.'),
        ),
    ]
