# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitmate_config', '0005_auto_20170222_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorespond_text', models.TextField(help_text='Text to be commented, upon opening pull request.', max_length=2500)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_commentor_repository', to='gitmate_config.Repository')),
            ],
        ),
    ]
