# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_welcome_commenter', '0003_auto_20170622_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='autorespond_text',
            field=models.TextField(help_text='Message', max_length=2500),
        ),
    ]
