# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitmate_config', '0009_auto_20170622_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_expire_limit', models.IntegerField(default=30, help_text='No. of days after which an issue is considered stale')),
                ('stale_label', models.CharField(default='status/STALE', help_text='Label to use for a marking pull requests and issues', max_length=100)),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gitmate_issue_stale_reminder_repository', to='gitmate_config.Repository')),
            ],
            options={
                'verbose_name_plural': 'settings',
                'abstract': False,
            },
        ),
    ]
