# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_stale_reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='issue_expire_limit',
            field=models.IntegerField(default=30, help_text='No. of days after which an issue is labelled stale'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='stale_label',
            field=models.CharField(default='status/STALE', help_text='Label to use for a marking stale issues', max_length=100),
        ),
    ]
