# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_issue_stale_reminder', '0004_auto_20171212_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='unassign',
            field=models.BooleanField(default=True, help_text='Unassign assignees if an issue goes stale'),
        ),
    ]
