# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_pr_size_labeller', '0004_auto_20170622_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='size_scheme',
            field=models.CharField(default='size/{size}', help_text='Label scheme to use, use {size} as placeholder', max_length=100),
        ),
    ]
