# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0009_auto_20170622_1147'),
        ('gitmate_test_approver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('head_sha', models.CharField(default='', max_length=40)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_approver_mr', to='gitmate_config.Repository')),
            ],
        ),
    ]
