# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGittRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('provider', models.CharField(default=None, max_length=64)),
                ('full_name', models.CharField(default=None, max_length=256)),
            ],
            options={
                'verbose_name_plural': 'igitt_repositories',
            },
        ),
        migrations.AlterUniqueTogether(
            name='igittrepository',
            unique_together=set([('provider', 'full_name')]),
        ),
    ]
