# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_logger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Error',
        ),
    ]
