# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 03:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0007_repository_plugins'),
        ('gitmate_code_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(default=None, max_length=40)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result_repository', to='gitmate_config.Repository')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='analysisresults',
            unique_together=set([('repo', 'sha')]),
        ),
    ]
