# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_code_analysis', '0005_auto_20170622_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='pr_based_analysis',
            field=models.BooleanField(default=True, help_text='Run analysis only for the head commit of a pull request'),
        ),
    ]
