# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_code_analysis', '0006_auto_20170706_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresults',
            name='coafile_location',
            field=models.CharField(default='.coafile', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='coafile_location',
            field=models.CharField(default='.coafile', max_length=255),
        ),
    ]
