# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_config', '0016_auto_20171213_1411'),
        ('gitmate_code_analysis', '0008_auto_20171205_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(default=None, max_length=40)),
                ('comment_id', models.CharField(max_length=20)),
                ('iid', models.CharField(max_length=20, null=True)),
                ('comment_type', models.CharField(max_length=30)),
                ('mr_number', models.IntegerField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_merge_request_repository', to='gitmate_config.Repository')),
            ],
        ),
    ]
