# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_auto_label_pending_or_wip', '0003_auto_20170622_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='pending_review_label',
            field=models.CharField(default='process/pending_review', help_text='Label for pull requests that need review', max_length=25),
        ),
        migrations.AlterField(
            model_name='settings',
            name='wip_label',
            field=models.CharField(default='process/WIP', help_text='Label for pull requests that are work in progress', max_length=25),
        ),
    ]
