# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_similar_issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='list_duplicates',
            field=models.BooleanField(default=True, help_text='Link duplicate issues in a comment'),
        ),
        migrations.AddField(
            model_name='settings',
            name='list_similar',
            field=models.BooleanField(default=True, help_text='Link similar issues in a comment'),
        ),
    ]
