# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitmate_config', '0007_repository_plugins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_based_analysis', models.BooleanField(default=True, help_text='Analyze full pull requests and not commit by commit')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitmate_code_analysis_repository', to='gitmate_config.Repository')),
            ],
        ),
    ]
