# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 05:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitmate_code_analysis', '0005_auto_20170622_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresults',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('ERROR', 'ERROR'), ('CANCELED', 'CANCELED'), ('RUNNING', 'RUNNING')], default='RUNNING', max_length=10),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
